In [ ]:
#! pip install webdriver_manager

In [ ]:
# Instalación de Selenium y el webdriver (esto normalmente se hace fuera del script)
!pip install selenium
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

In [ ]:
import random
from bs4 import BeautifulSoup
import re
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
import pandas as pd
import re
import time

In [2]:
service = Service('C:/Users/User/AppData/Local/binman/binman_chromedriver/win32/128.0.6613.121/chromedriver.exe')
driver = webdriver.Chrome(service=service)

In [3]:
# Abre la página de Sotheby's
driver.get("https://www.sothebys.com/en/auctions/2012/latin-american-art-n08862.html")

In [4]:
artworks = driver.find_elements(By.XPATH, '//li[@class="AuctionsModule-results-item"]')    
artworks_info = []
            
for artwork in artworks:
    try:
        author = artwork.find_element(By.XPATH, './/div[@class="title "]/a').text.split(". ")[1].strip()
    except:
        author = "N/A"

    try:
        title = artwork.find_element(By.XPATH, './/div[@class="description"]').text.strip()
    except:
        title = "N/A"

    try:
        estimate_text = artwork.find_element(By.XPATH, './/div[@class="estimate"]').text.replace("Estimate: ", "").strip()
        min_estimate, max_estimate = estimate_text.replace("USD", "").strip().split(" – ")
    except:
        min_estimate, max_estimate = "N/A", "N/A"

    try:
        sold_price = artwork.find_element(By.XPATH, './/div[@class="sold"]').text.replace("Lot Sold: ", "").strip()
    except:
        sold_price = "N/A"

    # Añade la información de la obra de arte a la lista
    artworks_info.append({
        "Author": author,
        "Title": title,
        "Min Estimate": min_estimate,
        "Max Estimate": max_estimate,
        "Sold Price": sold_price
    })
df=pd.DataFrame(artworks_info)        
df

,Author,Title,Min Estimate,Max Estimate,Sold Price
0,DIEGO RIVERA,Mujer con dalias,"40,000","60,000",
1,FERNANDO BOTERO,Naturaleza muerta con frutas,"40,000","50,000",
2,JOSÉ PANCETTI,Saquarema,"40,000","60,000",
3,HÉCTOR POLEO,Maternidad,"150,000","200,000",
4,EMILIANO DI CAVALCANTI,Natureza morta,"150,000","200,000",
5,MATTA,Mourir pour le pain (Composition 50F),"250,000","350,000",
6,LEONORA CARRINGTON,Santa Teresa en la cocina,"350,000","450,000",N/A
7,N/A,,"2,000,000","3,000,000",
8,CARLOS MÉRIDA,Fecundidad,"40,000","60,000",
9,FRANCISCO TOLEDO,Autorretrato,"90,000","120,000",
10,ARMANDO REVERÓN,Desnudo detrás de la mantilla,"700,000","900,000",
11,FERNANDO BOTERO,Donna Seduta,"300,000","350,000",

In [5]:
# Espera a que la página se cargue completamente
time.sleep(5)  # Ajusta el tiempo según sea necesario

# Encuentra el botón 'LOG IN' usando el XPath y haz clic en él
log_in_button = driver.find_element(By.XPATH, '//a[@data-text-content="Log In"]')
log_in_button.click()

# Espera a que la página de inicio de sesión se cargue
time.sleep(5)  # Ajusta el tiempo según sea necesario

# Encuentra el campo de email y contraseña, luego ingresa las credenciales
email_field = driver.find_element(By.XPATH, '//input[@placeholder="Email address"]')
password_field = driver.find_element(By.XPATH, '//input[@placeholder="Password"]')

email_field.send_keys("r.workshop.umd@gmail.com")
password_field.send_keys("Workshop123")

time.sleep(5)  # Ajusta el tiempo según sea necesario

# Encuentra y haz clic en el botón de 'Log in' por ID
login_button = driver.find_element(By.ID, 'login-button-id')
login_button.click()

In [10]:
driver.get("https://www.sothebys.com/en/auctions/2014/latin-american-art-n09223.html")

In [11]:
driver.refresh()

In [12]:
artworks = driver.find_elements(By.XPATH, '//li[@class="AuctionsModule-results-item"]')    
artworks_info = []
            
for artwork in artworks:
    try:
        author = artwork.find_element(By.XPATH, './/div[@class="title "]/a').text.split(". ")[1].strip()
    except:
        author = "N/A"

    try:
        title = artwork.find_element(By.XPATH, './/div[@class="description"]').text.strip()
    except:
        title = "N/A"

    try:
        estimate_text = artwork.find_element(By.XPATH, './/div[@class="estimate"]').text.replace("Estimate: ", "").strip()
        min_estimate, max_estimate = estimate_text.replace("USD", "").strip().split(" – ")
    except:
        min_estimate, max_estimate = "N/A", "N/A"

    try:
        sold_price = artwork.find_element(By.XPATH, './/div[@class="sold"]').text.replace("Lot Sold: ", "").strip()
    except:
        sold_price = "N/A"

    # Añade la información de la obra de arte a la lista
    artworks_info.append({
        "Author": author,
        "Title": title,
        "Min Estimate": min_estimate,
        "Max Estimate": max_estimate,
        "Sold Price": sold_price
    })
df=pd.DataFrame(artworks_info)        
df

,Author,Title,Min Estimate,Max Estimate,Sold Price
0,HÉRCULES BARSOTTI,Entidade múltipla III,"50,000","70,000",
1,WILLYS DE CASTRO,Objeto ativo: Duo,"40,000","60,000",
2,CILDO MEIRELES,Metros I,"175,000","225,000",
3,SERGIO CAMARGO,Untitled (Relief No. 196),"500,000","700,000",
4,CARLOS CRUZ-DIEZ,Physichromie 846,"150,000","200,000",
5,HÉLIO OITICICA,Metaesquema 198,"175,000","225,000",
6,MIRA SCHENDEL,"Untitled, from the series Droguinha (Little No...","400,000","600,000",
7,MATHÍAS GOERITZ,Untitled,"200,000","250,000",
8,GUNTHER GERZSO,Paisaje-Sur,"150,000","250,000",
9,DIEGO RIVERA,Pescadores de Acapulco (The Fishermen),"700,000","900,000",
10,FERNANDO BOTERO,Reclining Woman,"300,000","400,000",
11,RUFINO TAMAYO,Ofrenda de frutas,"2,000,000","3,000,000",

In [ ]:
driver.quit()